# BASIC LINEAR ALGEBRA AND ITS APPLICATIONS TO IMAGE DATA

## OUTLINE:
1. Changing Image illuminations
2. Slicing in Numpy Arrays
3. Cropping an Image region
4. Dot product and its application
5. Matrix transformation and its applications

# I, CHANING IMAGE ILLUMINATIONS: BASIC OpenCV

In [ ]:
# read and display grayscale image
import cv2
import matplotlib.pyplot as plt

# Load the image in grayscale
image = cv2.imread("image.jpg", cv2.IMREAD_GRAYSCALE)

# Display using Matplotlib
plt.imshow(image, cmap="gray")
plt.axis("off")  # Hide axes
plt.show()


# Increase the brightness of a grayscale image


In [21]:
# Convert N-D matrix to 1D: use method flatten()
import cv2
import numpy as np
grayscale_image = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
     dtype=np.uint8
)
print(grayscale_image)
aList = grayscale_image.flatten()
print(aList)
print(grayscale_image)
# Convert 1D to N-D
new_arr = aList.reshape((9, 1))
print(aList)
print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [28]:
# Increase the brightness of a grayscale image

def increase_brightness_customize(image_path, brightness_value, output_path):
    # Step1: Read image
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

    # Step2: Convert the image to a 10 list (flattened array)
    flattened_image = image.flatten()

    # Step3: Increase the brightness in the 1D list using a for loop
    brightened_1d = []
    for pixel_value in flattened_image:
        # Increase brightness and ensure pixel values are between 0 and 255
        brightened_pixel = pixel_value + brightness_value
        brightened_1d.append(np.clip(brightened_pixel, 0, 255))

    # Step4: Reshape the 1D list back to the original grayscale image shape
    brightened_image = np.array(brightened_1d).reshape(image.shape)

    # Save
    cv2.imwrite(output_path, brightened_image)
    return brightened_image

def increase_brightness_customizev2(image_path, brightness_value, output_path):
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    img = img.astype(float)

    img = img + brightness_value
    img = np.where(img < 0., 0., img)
    img = np.where(img > 255.,255., img)

    img = img.astype(np.uint8)
    cv2.imwrite(output_path, img)
# Main function
input_image_path = "image.jpg"
output_image_path = "image_brightness.jpg"
brightness_increase = -50
increase_brightness_customizev2(input_image_path, brightness_increase, output_image_path)

# NUMPY IN IMAGE DATA