# IMAGE DATA AND NUMPY
## OUTLINE

### NUMPY:
1. Numpy array creation
2. Indexing
3. Slicing
4. Where function

### Matrix operations:
1. Addtion
2. Subtraction
3. Multiplication
4. Division

### Vector operations:
1. Addtion
2. Subtraction
3. Multiplication
4. Division

### Image data:
1. Image applications: Read/Write an image, Copy an image
2. Background Subtraction

# NUMPY IN PYTHON

In [9]:
# Numpy array creation
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

arr = np.zeros(4)
print(arr)

arr = np.arange(1, 4, 2)
print(arr)

arr = np.random.rand(3)
print(arr)

arr = np.empty(3)
print(arr)

arr = np.array([[1, 2, 3], [1, 43, 5]], dtype=float)
print(arr)

arr = np.zeros((2, 3))
print(arr)

arr = np.full((1, 4), (2.0))
print(arr)



[1 2 3]
[0. 0. 0. 0.]
[1 3]
[0.30748642 0.3357895  0.92906778]
[0.30748642 0.3357895  0.92906778]
[[ 1.  2.  3.]
 [ 1. 43.  5.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[2. 2. 2. 2.]]


In [17]:
# Where function in numpy: np.where(condition, x, y)
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(np.where(arr % 2 == 0, 'even', 'odd'))
print(np.where(arr < 5, arr, arr + 10))
print(np.where(arr > 5, arr, -1))

[['odd' 'even' 'odd' 'even']
 ['odd' 'even' 'odd' 'even']]
[[ 1  2  3  4]
 [15 16 17 18]]
[[-1 -1 -1 -1]
 [-1  6  7  8]]


# VECTOR OPERATIONS

In [32]:
list1 = [1, 2, 3]
vector1 = np.array(list1)
print(vector1)
vector2 = np.array([4, 5, 6])
print(vector2)

# Vector addition
print(vector1 + vector2)
print(np.add(vector1, vector2))

# Vector subtraction
print(vector1 - vector2)
print(np.subtract(vector1, vector2))

# Vector division
print(vector1 / vector2)
print(np.divide(vector1, vector2))

# Vector multi
print(vector1 * vector2)
print(np.multiply(vector1, vector2))

[1 2 3]
[4 5 6]
[5 7 9]
[5 7 9]
[-3 -3 -3]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]
[ 4 10 18]
[ 4 10 18]


# MATRIX OPERATIONS

In [51]:
# Create a matrix
matrix1 = np.array([[1, 2], [3, 4]])
print(matrix1)

matrix2 = np.random.rand(2,2)
print(matrix2)

# Matrix addition
print(matrix1 + matrix2)
print(np.add(matrix1, matrix2))

# Matrix subtraction
print(matrix1 - matrix2)
print(np.subtract(matrix1, matrix2))

# Matrix division
print(matrix1 / matrix2)
print(np.divide(matrix1, matrix2))

# Matrix multiply
print(matrix1 * matrix2)
print(np.multiply(matrix1, matrix2))

[[1 2]
 [3 4]]
[[0.23531137 0.99852444]
 [0.31060057 0.32244126]]
[[1.23531137 2.99852444]
 [3.31060057 4.32244126]]
[[1.23531137 2.99852444]
 [3.31060057 4.32244126]]
[[0.76468863 1.00147556]
 [2.68939943 3.67755874]]
[[0.76468863 1.00147556]
 [2.68939943 3.67755874]]
[[ 4.24968844  2.00295548]
 [ 9.65870724 12.40536019]]
[[ 4.24968844  2.00295548]
 [ 9.65870724 12.40536019]]
[[0.23531137 1.99704888]
 [0.93180172 1.28976505]]
[[0.23531137 1.99704888]
 [0.93180172 1.28976505]]


# IMAGE DATA IN PYTHON

# BASIC OpenCV


In [63]:
# Load an image using OpenCV
import cv2

# read a grayscale image
data = cv2.imread('download.jpg', 1)
print(data.shape)


(162, 311, 3)


True

In [66]:
# Copy an image
image = cv2.imread('naruto.jpg', 1)
height, width, channel = image.shape

# Create an array
array_shape = (height, width, channel)
copy_image = np.zeros(array_shape)

# Copy
for i in range(height):
    for j in range(width):
        for k in range(channel):
            copy_image[i][j][k] = image[i][j][k]
# Save an image from a list
cv2.imwrite('copy.jpg', np.array(copy_image))
    

True

In [8]:
# BACKGROUND SUBTRACTION
## Extract background/foreground
import cv2
import numpy as np

# Resize image (OpenCV)
original_matrix = np.array(
    [[4, 8],
     [2, 3]],
    dtype=np.uint8
)
# Resize with cv2.INTER_LINEAR
resized_matrix = cv2.resize(original_matrix, (4, 4),
                            interpolation=cv2.INTER_LINEAR)
print(resized_matrix)

# Absolute difference in OpenCV



[[4 5 7 8]
 [4 4 6 7]
 [3 3 4 4]
 [2 2 3 3]]


In [18]:
# Absolute difference in OpenCV
matrix_A = np.array(
    [[4, 8, 5, 6],
     [2, 28, 15, 5],
     [3, 5, 2, 5]],
    dtype=np.uint8
)

matrix_B = np.array(
    [[4, 8, 5, 6],
     [2, 8, 4, 5],
     [3, 5, 2, 5]],
    dtype=np.uint8
)
difference = cv2.absdiff(matrix_A, matrix_B)
print(difference)

# Simple thresholding in OpenCV
_,difference_binary = cv2.threshold(
    difference, 15, 255, cv2.THRESH_BINARY
)
difference_binary

[[ 0  0  0  0]
 [ 0 20 11  0]
 [ 0  0  0  0]]


array([[  0,   0,   0,   0],
       [  0, 255,   0,   0],
       [  0,   0,   0,   0]], dtype=uint8)

In [39]:
# Extract background/foreground

bg = cv2.imread('background.jpg', 1)
print(bg)
bg = cv2.resize(bg, (500, 480))

img = cv2.imread('image.jpg', 1)
print(img)
img = cv2.resize(img, (500, 480))

difference = cv2.absdiff(bg, img)
_, difference_binary = cv2.threshold(
    difference, 100, 255, cv2.THRESH_BINARY)

new_bg = cv2.imread('fake_background.jpg')
new_bg = cv2.resize(new_bg, (500, 480))

output = np.where(difference_binary==0, new_bg, img)
cv2.imwrite('output.jpg', output)

[[[147 159 161]
  [147 159 161]
  [147 159 161]
  ...
  [162 174 178]
  [162 174 178]
  [162 174 178]]

 [[147 159 161]
  [147 159 161]
  [147 159 161]
  ...
  [162 174 178]
  [162 174 178]
  [162 174 178]]

 [[147 159 161]
  [147 159 161]
  [147 159 161]
  ...
  [162 174 178]
  [162 174 178]
  [162 174 178]]

 ...

 [[132 139 142]
  [132 139 142]
  [132 139 142]
  ...
  [152 158 163]
  [152 158 163]
  [152 158 163]]

 [[132 139 142]
  [132 139 142]
  [132 139 142]
  ...
  [153 159 164]
  [153 159 164]
  [153 159 164]]

 [[132 139 142]
  [132 139 142]
  [132 139 142]
  ...
  [153 159 164]
  [154 160 165]
  [154 160 165]]]
[[[217 226 223]
  [216 225 222]
  [216 225 222]
  ...
  [192 201 198]
  [192 201 198]
  [192 201 198]]

 [[215 224 221]
  [215 224 221]
  [215 224 221]
  ...
  [192 201 198]
  [192 201 198]
  [192 201 198]]

 [[215 224 221]
  [214 223 220]
  [214 223 220]
  ...
  [192 201 198]
  [192 201 198]
  [192 201 198]]

 ...

 [[ 54  54  54]
  [ 57  57  57]
  [ 61  61  61]
  ..

True